### ISSUE TITLE
Surface Go hangs on boot with 5.8.14-surface kernel.

### ISSUE THREAD

**Issue by pmsjt** [linux-surface/kernel#63] opened 2020-10-11 23:31 UTC
Still boots fine when I select 5.8.12-surface.

**Comment by pmsjt** [comment] 2020-10-11 23:33
Same exact kernel boots fine on my Book2. Of these 2 devices, this issue only seems to affect the Go1.

**Comment by kitakar5525** [comment] 2020-10-12 02:58
There is a report that SGO2 won't boot after applying commit https://github.com/gregkh/linux/commit/953fc770d069b167266d9d9ccfef0455fcfdc070 (added on upstream v5.8.13) (https://github.com/linux-surface/linux-surface/issues/91#issuecomment-697990030). So, the commit seems to be really causing issue on the SGO series...

I saw the journal log in the comment, but I couldn't find what is wrong.

You can get a kernel log of previous boot by `journalctl --dmesg --output=short-monotonic --no-hostname --boot=-1`. Can you also attach the output here?
1. boot with 5.8.14-surface
2. restart and boot with bootable kernel (e.g., 5.8.12-surface)
3. get the kernel log of previous boot

**Comment by pmsjt** [comment] 2020-10-12 05:54
> journalctl --dmesg --output=short-monotonic --no-hostname --boot=-1

Thanks @kitakar5525 

I am attaching a few files. The TXT file is the output of the command you asked for (log from previous boot session). The two images help tell the story.

The machine boots for a bit and then freezes at the point captured by the first photo (usbhid). It lingers there for a long time. At least 5 minutes. At that point some timeout expires and boot continues to progress a bit more till it hits the point captured by the second picture (gtk-common-themes). I left the machine in this state for a very long time and it does not progress any longer. This seems to be the final resting place.

[last_boot_dmesg.txt](https://github.com/linux-surface/kernel/files/5363168/last_boot_dmesg.txt)
![IMG_5835](https://user-images.githubusercontent.com/40605312/95710027-b924ad80-0c14-11eb-993f-15a1ff7a7170.JPG)
![IMG_5836](https://user-images.githubusercontent.com/40605312/95710038-bcb83480-0c14-11eb-9165-f96326d12b70.JPG)

**Comment by pmsjt** [comment] 2020-10-12 06:22
Another datapoint: If I add the "nomodeset" kerrnel option, the boot process still does that long pause after enumerating the USB devices, but after it resumes from that point, it continues to boot and eventually completed.

So, "nomodeset" doesn't make all the symptoms go away, but it does have an effect.

**Comment by kbingham** [comment] 2020-10-12 08:44
```
[    2.799587] kernel: usbhid: USB HID core driver
[  122.286040] kernel: EXT4-fs (nvme0n1p2): mounted filesystem with ordered data mode. Opts: (null)
```

Hard to be sure here, 120 seconds (a 2 minute timeout?) from the USB HID driver to the point it was able to mount the filesystem...

Can't easily remove USBHID, and we can't remove the filesystems so not easy to bisect those... but I think this needs more information.

To really identify this issue, we should bisect the kernels between 5.8.12 and 5.8.14 - that would identify/confirm the exact commit causing the issue....

@pmsjt Is that something you're able to do? It requires building the kernels manually, and using 'git bisect' to decide which kernel commit to build - test, and iterate until the bisection states explicitly which commit causes the fault.

Or if there really is some confidence that this commit is causing the problems, try reverting it (git revert 21653a4) to see if the issue is resolved with it gone.

**Comment by kitakar5525** [comment] 2020-10-12 09:22
In addition to what kbingham mentioned: It looks like the Ubuntu config sets usbhid driver as module. So, something might be revealed by not loading the module. To do so, add `module_blacklist=usbhid` to your bootloader.

**Comment by B-Woody** [comment] 2020-10-13 01:04
I have Microsoft Surface Go 2 ( with Intel Pentium Gold CPU ) that's running Fedora 32. It worked flawlessly until the update to kernel to 5.8.13-200 was installed. When I try to boot kernel 5.8.13-300 the system freezes very early in the boot process with the last line of output being displayed:

`clocksource: Switched to clocksource tsc`

I checked on the Surface Linux subreddit and another user with the Surface Go 2 confirmed that they had the same issue on kernel 5.8.13 but in Arch Linux. This would lead me to believe that it's a kernel issue and not Fedora specific.

I saw this commit on the kernel 5.8.13 changelog that has something to do with clocksource drivers and I think it could be related ( but it might be a coincidence )

https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.8.13
```
commit 510c51ff61e3313426f4103dc12766156335a8db
Author: Tony Lindgren <tony@atomide.com>
Date:   Mon Aug 17 12:24:28 2020 +0300

    clocksource/drivers/timer-ti-dm: Do reset before enable
    
    commit 164805157f3c6834670afbaff563353c773131f1 upstream.
```

I'm willing to test any potential fixes on my hardware if that helps.

Kernel 5.8.12 continues to work fine if I manually select it from GRUB so I'm doing that in the meantime.

**Comment by B-Woody** [comment] 2020-10-14 04:16
> Or if there really is some confidence that this commit is causing the problems, try reverting it (git revert [21653a4](https://github.com/linux-surface/kernel/commit/21653a4181ff292480599dad996a2b759ccf050f)) to see if the issue is resolved with it gone.

If I get some time on the weekend I may be able to use my Surface Go 2 to at least give this a try and/or check if the issue occurs on a 5.9 kernel

**Comment by tml89** [comment] 2020-10-14 04:56
Got the same issue with sgo 1 as b-woody.

**Comment by pmsjt** [comment] 2020-10-14 05:43
> In addition to what kbingham mentioned: It looks like the Ubuntu config sets usbhid driver as module. So, something might be revealed by not loading the module. To do so, add `module_blacklist=usbhid` to your bootloader.

That doesn't seem to solve either problem. Maybe USBHID is just a read herring and the real problem is affecting what gets printed after and not before.

There seem to have been quite a few developments since I last checked the thread. At the moment, which is the commit with the most suspicion (and the best candidate for a git revert + rebuild) ?

Thanks.

**Comment by kitakar5525** [comment] 2020-10-14 07:52
> > In addition to what kbingham mentioned: It looks like the Ubuntu config sets usbhid driver as module. So, something might be revealed by not loading the module. To do so, add `module_blacklist=usbhid` to your bootloader.
> 
> That doesn't seem to solve either problem. Maybe USBHID is just a read herring and the real problem is affecting what gets printed after and not before.

I see...

> There seem to have been quite a few developments since I last checked the thread. At the moment, which is the commit with the most suspicion (and the best candidate for a git revert + rebuild) ?

The first candidate to revert I think is `i2c: core: Call i2c_acpi_install_space_handler() before i2c_acpi_register_devices()`
- for v5.9-rc6 and later, 21653a4181ff
- for v5.8.13 and later, 953fc770d069

But if I assume that this commit is the cause, I don't have any idea why this commit causes an issue on the SGO series. If reverting this helped, I'd suggest reporting this to the Bugzilla (https://bugzilla.redhat.com/show_bug.cgi?id=1842039) referenced by the commit.

The next candidate to revert B-Woody mentioned is `clocksource/drivers/timer-ti-dm: Do reset before enable`
- for v5.9-rc7 and later, 164805157f3c
- for v5.8.13 and later, 510c51ff61e3

Ideally, as kbingham mentioned, doing `git bisect` is the best idea though.
(from https://github.com/linux-surface/kernel/issues/63#issuecomment-706975891)
> To really identify this issue, we should bisect the kernels between 5.8.12 and 5.8.14 - that would identify/confirm the exact commit causing the issue....

**Comment by jwrdegoede** [comment] 2020-10-14 08:59
Author of the 'i2c: core: Call i2c_acpi_install_space_handler() before i2c_acpi_register_devices()' commit here, ugh I certainly don't hope that it is the root cause. But with ACPI being ACPI and with how horribly Microsoft (of all "people") abuses ACPI in their surface line I would not be surprised if it is the root cause.

I do not expect the 'clocksource/drivers/timer-ti-dm: Do reset before enable' commit to have any impact, that changes code for the TI OMAP series chips.

Can someone provide me an acpidump of the Microsoft Surface Go 2 please ?  Then I can check if the i2c-acpi commit is expected to have any influence there.

**Comment by kbingham** [comment] 2020-10-14 09:05
Hi Hans ;-) Thanks for jumping over! Did you find this thread from somewhere ?

ACPI dumps for this device are at : 
https://github.com/linux-surface/acpidumps/tree/master/surface_go

**Comment by kitakar5525** [comment] 2020-10-14 09:07
and acpidump for Surface Go 2 is here:
https://github.com/linux-surface/acpidumps/tree/master/surface_go_2

**Comment by kbingham** [comment] 2020-10-14 09:18
Ok, I don't think anyone else will, and I don't really have time, but I'll kick off a bisect of this (assuming I can reproduce it).
I have been running a v5.9 (linux-media/master) kernel, and not hit this.

I've just started a build of 5.8.14, from linux-stable. Is that the confirmed point at which the boots fail? (I can only test on an SGO2)

**Comment by jwrdegoede** [comment] 2020-10-14 09:24
> Hi Hans ;-) Thanks for jumping over! Did you find this thread from somewhere ?

I found this thread through:
https://bugzilla.redhat.com/show_bug.cgi?id=1886249

> ACPI dumps for this device are at :
> https://github.com/linux-surface/acpidumps/tree/master/surface_go

Thanks, so I took a look at the Go *2* acpidump, since the reports about the i2c-acpi commit were related to the go2 and nothing stands out there. None of the _STA methods for the i2c devices relies on i2c opregion access, so the order of registering the opregion vs checking for i2c devices on the controller (which calls the _STA method) should not matter.

**Comment by kitakar5525** [comment] 2020-10-14 09:27
> I've just started a build of 5.8.14, from linux-stable. Is that the confirmed point at which the boots fail? (I can only test on an SGO2)

According to the reddit (https://www.reddit.com/r/SurfaceLinux/comments/j71vyl/surface_go_2_wont_boot_kernel_after_update_to/), it started failing from `5.8.13` on Fedora and Arch kernels.

**Comment by kbingham** [comment] 2020-10-14 09:32
Ok, good news is, I can replicate this on the SGO2 device I have on the linux-stable 5.8.14 kernel. I'll bisect it from 5.8.12.

**Comment by kbingham** [comment] 2020-10-14 10:48
And the bad news (for @jwrdegoede ) is that I'm afraid bisecting does indeed fall on
 953fc770d069 ("i2c: core: Call i2c_acpi_install_space_handler() before i2c_acpi_register_devices()")

 https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=953fc770d069b1

**Comment by kbingham** [comment] 2020-10-14 11:03
Completing (confirming) the puzzle, a rebuild of v5.8.14, with 953fc77 ("i2c: core: Call i2c_acpi_install_space_handler() before i2c_acpi_register_devices()") reverted boots fine on the SGO2 for me.

**Comment by jwrdegoede** [comment] 2020-10-14 11:12
Ugh, thank you for doing the bisect. So I guess we need to get a revert for that send to GkH, for the stable series, can you send that with me in the Cc? Then I'll ack it right away, Please include a link to this issue in the revert commit message.

But that revert is going to regress these issues:
https://bugzilla.redhat.com/show_bug.cgi?id=1842039
https://bugzilla.redhat.com/show_bug.cgi?id=1871793
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1861610

So there really is no winning option here :| 

The commit in question fixes the touchpad not working on several recent Lenovo models (see the above bugs). What it does it makes the method (opregion) to access the i2c bus from ACPI code available to the ACPI code before calling the status method of ACPI devices on that i2c-bus. This status method tells us if the device is actually present or not and on those Thinkpads the status method did an i2c check, so we needed to register the i2c opregion before checking for new devices.

Registering the i2c opregion earlier seemed like an obvious solution, but I was already afraid we would hit an issue on some device because of this, because of ACPI being ACPI.

The weird thing is I see no i2c opregion use in the _STA methods for i2c devices in the GO2 DSDT (and I also checked the SSDTs), so this commit really should not make a difference.

Any chance someone following this issue with a go2 can dig a bit deeper and try to figure on why that commit exactly is breaking things ?

**Comment by kbingham** [comment] 2020-10-14 11:46
Ugh :-( Bringing back fixed regressions doesn't sound good - but I fear a non-working touchpad is better than a non-booting device.

Half of one and ...

So it appears when the boot hangs, it gets far enough that I can ssh in and grab a dmesg log, which shows the points that are hung. Seems helpful.

I'll attach those here, but also reply with that information on the i2c-devel mailing list regarding the upstream commit.

[5.9.21653a4-hang.dmesg.log](https://github.com/linux-surface/kernel/files/5377909/5.9.21653a4-hang.dmesg.log)


There's a few backtraces there, 

- tps68470_probe
and
- i915_driver_probe

I suspect of course if we're blocking the i915 driver that's the reason it fails to load to a desktop.

**Comment by qzed** [comment] 2020-10-14 11:48
Don't have a Go 2 to test, but could the `acpi_walk_dep_device_list()` call inside `i2c_acpi_install_space_handler()` be a problem? With 953fc77 that gets called before the devices have been registered. Could that lead to dependencies being marked as present event though they haven't been fully set up yet?

**Comment by jwrdegoede** [comment] 2020-10-14 11:57
> Don't have a Go 2 to test, but could the `acpi_walk_dep_device_list()` call inside `i2c_acpi_install_space_handler()` be a problem? With [953fc77](https://github.com/linux-surface/kernel/commit/953fc770d069b167266d9d9ccfef0455fcfdc070) that gets called before the devices have been registered. Could that lead to dependencies being marked as present event though they haven't been fully set up yet?

Oh, that is a very good point, I missed that i2c_acpi_install_space_handler() was also doing that (I assumed it only did what its name suggest). Yeah that should be moved to the end of i2c_acpi_register_devices().

I'm preparing a patch for that now.

**Comment by kbingham** [comment] 2020-10-14 11:59
Great, I'll leave all this in your hands then. A fix on top is better than a revert !

**Comment by jwrdegoede** [comment] 2020-10-14 12:10
@kbingham ok I have a test based on @qzed's suggestion ready for testing here:
https://fedorapeople.org/~jwrdegoede/0001-i2c-core-Restore-acpi_walk_dep_device_list-getting-c.patch

Can you please give this a try, either on 5.8.14 or on 5.9 (without a revert of the troublesome commit) is fine.

Note I've given you both report/test resp. suggested-by credits in the patch, let me know if you want me to NOT do that.

**Comment by kbingham** [comment] 2020-10-14 12:28
Thanks @jwrdegoede - I can confirm this now works. Booted successfully with a v5.9 kernel + your patch.

**Comment by jwrdegoede** [comment] 2020-10-14 14:43
Thank you for testing, I have submitted the fix upstream now, with a plea for gkh to pick this up for the stable series even though it is not yet in Linus' tree.

Lets keep our fingers crossed that gkh is willing to pick it up earlier :)

**Comment by qzed** [comment] 2020-10-16 17:56
I've added this patch to our kernel tree and patchset for now.

**Closed by qzed** 2020-10-16 17:56 UTC
Labels: C: bug (upstream), D: Surface Go 1, D: Surface Go 2
